In [3]:
from google.colab import drive
drive.mount('/content/drive')
!ls drive/MyDrive/ML/Praktikum1

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
AkmalNajib_202010225167_NaiveBayes.csv	news_articles.csv      Peta.png
Automobile_data.csv			penjualanmobilNB.xlsx  tenis.xlsx

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [8]:
dataset = pd.read_csv("drive/MyDrive/ML/Praktikum1/AkmalNajib_202010225167_NaiveBayes.csv")

In [9]:
dataset

    No  Tahun Pembuatan     Merk   Jarak       Harga
0    1             2012  Hyundai  Sedang   300000000
1    2             2014      Kia   Dekat  1000000000
2    3             2016  Genesis    Jauh   300000000
3    4             2012  Hyundai  Sedang  1000000000
4    5             2014      Kia   Dekat  1000000000
5    6             2016  Genesis  Sedang   300000000
6    7             2012  Hyundai   Dekat   500000000
7    8             2014      Kia    Jauh   300000000
8    9             2016  Genesis   Dekat  1000000000
9   10             2012  Hyundai  Sedang   300000000
10  11             2014      Kia    Jauh   500000000
11  12             2016  Genesis    Jauh  1000000000
12  13             2012  Hyundai  Sedang   500000000
13  14             2014      Kia    Jauh   300000000
14  15             2016  Genesis  Sedang   500000000
15  16             2012  Hyundai   Dekat   300000000
16  17             2014      Kia  Sedang  1000000000
17  18             2016  Genesis    Jauh   500000000
18  19             2012  Hyundai  Sedang   300000000
19  20             2014      Kia    Jauh  1000000000

In [10]:
x = dataset.iloc[:, :-1]
x = x.apply(LabelEncoder().fit_transform)
x

    No  Tahun Pembuatan  Merk  Jarak
0    0                0     1      2
1    1                1     2      0
2    2                2     0      1
3    3                0     1      2
4    4                1     2      0
5    5                2     0      2
6    6                0     1      0
7    7                1     2      1
8    8                2     0      0
9    9                0     1      2
10  10                1     2      1
11  11                2     0      1
12  12                0     1      2
13  13                1     2      1
14  14                2     0      2
15  15                0     1      0
16  16                1     2      2
17  17                2     0      1
18  18                0     1      2
19  19                1     2      1

In [11]:
y = dataset.iloc[:, 4]
y

0      300000000
1     1000000000
2      300000000
3     1000000000
4     1000000000
5      300000000
6      500000000
7      300000000
8     1000000000
9      300000000
10     500000000
11    1000000000
12     500000000
13     300000000
14     500000000
15     300000000
16    1000000000
17     500000000
18     300000000
19    1000000000
Name: Harga, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size=0.5, random_state=322)

In [27]:
from sklearn.naive_bayes import GaussianNB
#Mengaktifkan/Memanggil/Membuat fungsi klasifikasi naive bayes
modelnb = GaussianNB()
#Memasukan data Train pada fungsi klasifikasi naive bayes
nbtrain = modelnb.fit(xTrain, yTrain)

In [28]:
#Menentukan hasil prediksi dari xTest
yPrediction = nbtrain.predict(xTest)
yPrediction

array([1000000000, 1000000000, 1000000000, 1000000000, 1000000000,
        300000000,  300000000, 1000000000, 1000000000, 1000000000])

In [29]:
np.array(yTest)

array([ 300000000, 1000000000,  500000000,  300000000, 1000000000,
        500000000,  500000000,  300000000,  500000000, 1000000000])

In [30]:
nbtrain.predict_proba(xTest)

array([[0.31663268, 0.        , 0.68336732],
       [0.2561013 , 0.        , 0.7438987 ],
       [0.04967028, 0.        , 0.95032972],
       [0.02392082, 0.        , 0.97607918],
       [0.10826579, 0.        , 0.89173421],
       [0.65589017, 0.        , 0.34410983],
       [0.75167781, 0.        , 0.24832219],
       [0.48497071, 0.        , 0.51502929],
       [0.17166995, 0.        , 0.82833005],
       [0.13472615, 0.        , 0.86527385]])

In [31]:
y_actual = pd.Series(np.array(yTest), name = "actual")
y_pred = pd.Series(yPrediction, name = "prediction")
df_confusion = pd.crosstab(y_actual, y_pred)
df_confusion

prediction  300000000   1000000000
actual
300000000            0           3
500000000            2           2
1000000000           0           3

In [32]:
from sklearn.metrics import classification_report
print(classification_report(yTest, yPrediction))

              precision    recall  f1-score   support

   300000000       0.00      0.00      0.00         3
   500000000       0.00      0.00      0.00         4
  1000000000       0.38      1.00      0.55         3

    accuracy                           0.30        10
   macro avg       0.12      0.33      0.18        10
weighted avg       0.11      0.30      0.16        10

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))